import { createHmac, timingSafeEqual } from "node:crypto";
import { prisma } from "../database";

type PinnedRepository={name:string;fullName:string;url:string;description:string|null;source:"github-profile-pinned"|"environment"};
type Repo={id:number;name:string;full_name:string;html_url:string;default_branch:string;description:string|null;language:string|null;stargazers_count:number;topics?:string[];pushed_at:string;updated_at:string};
type TreeItem={path:string;type:string;sha:string;size?:number};
const ORG="FeexSystems", PROFILE_URL=`https://github.com/${ORG}`, API="https://api.github.com";
const TEXT=/\.(ts|tsx|js|jsx|mjs|cjs|py|go|rs|java|kt|php|rb|cs|cpp|c|h|hpp|sql|prisma|json|yaml|yml|md|mdx|html|css|scss|vue|svelte|sh|toml|xml)$/i;
const MAX_FILES=Number(process.env.WORLD_MODEL_MAX_FILES||300);

async function gh(path:string){const r=await fetch(`${API}${path}`,{headers:{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",...(process.env.GITHUB_TOKEN?{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`}:{})}});if(!r.ok)throw new Error(`GitHub ${r.status}: ${await r.text()}`);return r.json();}
const key=(p:string,v:string)=>`${p}_${createHmac("sha256","feex-wm").update(v).digest("hex").slice(0,24)}`;

function configuredPinnedRepositories():PinnedRepository[]{const raw=process.env.GITHUB_PINNED_REPOSITORIES?.trim();if(!raw)return[];return raw.split(",").map(v=>v.trim()).filter(Boolean).map(repository=>({name:repository.split("/").pop()||repository,fullName:repository.includes("/")?repository:`${ORG}/${repository}`,url:`https://github.com/${repository.includes("/")?repository:`${ORG}/${repository}`}`,description:null,source:"environment" as const}));}

export async function discoverPinnedRepositories():Promise<PinnedRepository[]>{
  const configured=configuredPinnedRepositories(); if(configured.length)return configured;
  const response=await fetch(PROFILE_URL,{headers:{Accept:"text/html","User-Agent":"FEEXSYSTEMS-World-Model/1.0"}}); if(!response.ok)throw new Error(`GitHub profile request failed: ${response.status}`);
  const html=await response.text(); const pinned=html.match(/pinned-item-list[^>]*>([\s\S]*?)<\/ol>/i); if(!pinned)throw new Error("GitHub pinned repository section was not found; refusing to infer unrelated profile links");
  const repositories=new Map<string,PinnedRepository>(); const pattern=new RegExp(`href=[\"']\/${ORG}\/([^\"'#?]+)[\"'][^>]*>`,"gi"); let m:RegExpExecArray|null;
  while((m=pattern.exec(pinned[1]))!==null){const name=m[1].replace(/\/$/,"");if(name&&!name.startsWith(".")&&!repositories.has(name))repositories.set(name,{name,fullName:`${ORG}/${name}`,url:`https://github.com/${ORG}/${name}`,description:null,source:"github-profile-pinned"});}
  return [...repositories.values()].slice(0,6);
}

export async function ensureWorldModelTables(){
  const sql=[
    `CREATE TABLE IF NOT EXISTS world_model_projects (id TEXT PRIMARY KEY, repository TEXT NOT NULL UNIQUE, name TEXT NOT NULL, owner TEXT NOT NULL, url TEXT NOT NULL, description TEXT, visibility TEXT, is_pinned BOOLEAN NOT NULL DEFAULT FALSE, source TEXT NOT NULL DEFAULT 'github', metadata JSONB NOT NULL DEFAULT '{}'::jsonb, first_observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), last_observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
    `ALTER TABLE world_model_projects ADD COLUMN IF NOT EXISTS repo_id BIGINT`,
    `CREATE TABLE IF NOT EXISTS world_model_evidence (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES world_model_projects(id) ON DELETE CASCADE, evidence_type TEXT NOT NULL, source_url TEXT NOT NULL, source_ref TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, observed_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
    `CREATE TABLE IF NOT EXISTS world_model_artifacts (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES world_model_projects(id) ON DELETE CASCADE, path TEXT NOT NULL, sha TEXT NOT NULL, kind TEXT NOT NULL, size BIGINT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(project_id,path))`,
    `CREATE TABLE IF NOT EXISTS world_model_technologies (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, category TEXT, metadata JSONB NOT NULL DEFAULT '{}'::jsonb)`,
    `CREATE TABLE IF NOT EXISTS world_model_relationships (id TEXT PRIMARY KEY, source_id TEXT NOT NULL, target_id TEXT NOT NULL, relation TEXT NOT NULL, metadata JSONB NOT NULL DEFAULT '{}'::jsonb, UNIQUE(source_id,target_id,relation))`,
    `CREATE TABLE IF NOT EXISTS world_model_events (id TEXT PRIMARY KEY, project_id TEXT REFERENCES world_model_projects(id) ON DELETE CASCADE, event_type TEXT NOT NULL, commit_sha TEXT, changed_paths JSONB NOT NULL DEFAULT '[]', payload JSONB NOT NULL DEFAULT '{}', occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`,
    `CREATE INDEX IF NOT EXISTS world_model_projects_pinned_idx ON world_model_projects(is_pinned)`,`CREATE INDEX IF NOT EXISTS world_model_evidence_project_idx ON world_model_evidence(project_id)`,`CREATE INDEX IF NOT EXISTS world_model_artifacts_project_idx ON world_model_artifacts(project_id)`,`CREATE INDEX IF NOT EXISTS world_model_events_project_idx ON world_model_events(project_id,occurred_at DESC)`,
  ]; for(const statement of sql)await prisma.$executeRawUnsafe(statement);
}

function techs(repo:Repo,files:TreeItem[],text:string){const l=text.toLowerCase(),out=new Set<string>();if(repo.language)out.add(repo.language);const sig:Record<string,string[]>={React:["react"],TypeScript:["typescript","tsconfig"],Vite:["vite"],"Next.js":["next"],"Node.js":["express","node"],PostgreSQL:["postgres","postgresql","prisma"],Prisma:["prisma"],Redis:["redis","ioredis"],Docker:["docker","dockerfile"],"Three.js":["three","react-three"],TailwindCSS:["tailwind"],Supabase:["supabase"],Python:["python","pyproject","requirements.txt"],Kubernetes:["kubernetes","helm","k8s"],GraphQL:["graphql"],WebSockets:["socket.io","websocket"]};for(const[n,needles]of Object.entries(sig))if(needles.some(n=>l.includes(n)||files.some(f=>f.path.toLowerCase().includes(n))))out.add(n);return[...out];}

export async function syncPinnedProjects(){await ensureWorldModelTables();const repos=await discoverPinnedRepositories();for(const r of repos){const repo=await gh(`/repos/${r.fullName}`)as Repo;await syncRepository(repo,r);}return repos;}

export async function syncRepository(repo:Repo,pinned?:PinnedRepository,changedPaths:string[]=[]){
  await ensureWorldModelTables();const projectId=`github:${repo.full_name}`;
  await prisma.$executeRawUnsafe(`INSERT INTO world_model_projects(id,repository,name,owner,url,description,is_pinned,source,metadata,repo_id,last_observed_at) VALUES($1,$2,$3,$4,$5,$6,$7,'github',$8::jsonb,$9,NOW()) ON CONFLICT(repository) DO UPDATE SET name=EXCLUDED.name,url=EXCLUDED.url,description=COALESCE(EXCLUDED.description,world_model_projects.description),is_pinned=EXCLUDED.is_pinned,metadata=EXCLUDED.metadata,repo_id=EXCLUDED.repo_id,last_observed_at=NOW()`,projectId,repo.full_name,repo.name,ORG,repo.html_url,repo.description,Boolean(pinned),JSON.stringify({discovery:pinned?.source||"github",stars:repo.stargazers_count,pushedAt:repo.pushed_at,updatedAt:repo.updated_at,defaultBranch:repo.default_branch,language:repo.language,topics:repo.topics||[]}),repo.id);
  if(pinned)await prisma.$executeRawUnsafe(`INSERT INTO world_model_evidence(id,project_id,evidence_type,source_url,source_ref,metadata) VALUES($1,$2,'repository-discovery',$3,$4,$5::jsonb) ON CONFLICT(id) DO UPDATE SET observed_at=NOW(),metadata=EXCLUDED.metadata`,key("evidence",repo.full_name),projectId,PROFILE_URL,"profile-pinned",JSON.stringify({repository:repo.full_name}));
  const tree=await gh(`/repos/${repo.full_name}/git/trees/${repo.default_branch}?recursive=1`)as{tree:TreeItem[]};const files=tree.tree.filter(f=>f.type==="blob"&&TEXT.test(f.path)).slice(0,MAX_FILES);const target=changedPaths.length?new Set(changedPaths):null;const selected=target?files.filter(f=>target.has(f.path)):files;let aggregate=`${repo.name} ${repo.description||""} ${repo.language||""}`;const artifacts:string[]=[];
  for(const f of selected){const artifactId=key("artifact",`${repo.full_name}:${f.path}`);const kind=f.path.toLowerCase()==="readme.md"?"documentation":/(package.json|requirements.txt|pyproject.toml|Cargo.toml|go.mod)$/.test(f.path)?"manifest":"source";await prisma.$executeRawUnsafe(`INSERT INTO world_model_artifacts(id,project_id,path,sha,kind,size,metadata) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) ON CONFLICT(project_id,path) DO UPDATE SET sha=EXCLUDED.sha,kind=EXCLUDED.kind,size=EXCLUDED.size,metadata=EXCLUDED.metadata,updated_at=NOW()`,artifactId,projectId,f.path,f.sha,kind,f.size||null,JSON.stringify({source:"github"}));await prisma.$executeRawUnsafe(`INSERT INTO world_model_evidence(id,project_id,evidence_type,source_url,source_ref,metadata) VALUES($1,$2,'artifact',$3,$4,$5::jsonb) ON CONFLICT(id) DO UPDATE SET observed_at=NOW()`,key("evidence",`${repo.full_name}:${f.path}:${f.sha}`),projectId,`https://github.com/${repo.full_name}/blob/${repo.default_branch}/${f.path}`,f.sha,JSON.stringify({artifactId}));artifacts.push(f.path);if(f.path==="README.md"||f.path==="package.json"){try{const raw=await gh(`/repos/${repo.full_name}/contents/${encodeURIComponent(f.path)}?ref=${repo.default_branch}`)as{content?:string};if(raw.content)aggregate+=Buffer.from(raw.content.replace(/\n/g,""),"base64").toString("utf8");}catch{}}}
  for(const name of techs(repo,files,aggregate)){const tid=key("tech",name.toLowerCase());await prisma.$executeRawUnsafe(`INSERT INTO world_model_technologies(id,name,category) VALUES($1,$2,'technology') ON CONFLICT(name) DO NOTHING`,tid,name);await prisma.$executeRawUnsafe(`INSERT INTO world_model_relationships(id,source_id,target_id,relation,metadata) VALUES($1,$2,$3,'USES',$4::jsonb) ON CONFLICT DO NOTHING`,key("rel",`${projectId}:USES:${tid}`),projectId,tid,JSON.stringify({source:"repository-analysis"}));}
  await prisma.$executeRawUnsafe(`INSERT INTO world_model_events(id,project_id,event_type,changed_paths,payload) VALUES($1,$2,$3,$4::jsonb,$5::jsonb)`,key("event",`${repo.full_name}:${Date.now()}`),projectId,changedPaths.length?"incremental_sync":"repository_sync",JSON.stringify(artifacts),JSON.stringify({repository:repo.full_name,branch:repo.default_branch}));
  return{projectId,repository:repo.full_name,artifacts:artifacts.length,technologies:techs(repo,files,aggregate)};
}

export async function getPinnedWorldModelProjects(){await ensureWorldModelTables();return prisma.$queryRawUnsafe(`SELECT id,repository,name,owner,url,description,visibility,is_pinned AS "isPinned",source,metadata,first_observed_at AS "firstObservedAt",last_observed_at AS "lastObservedAt" FROM world_model_projects WHERE is_pinned=TRUE ORDER BY last_observed_at DESC`);}
export async function retrieveWorld(query:string,limit=12){await ensureWorldModelTables();const q=`%${query.trim().replace(/[%_]/g,"\\$&")}%`;const projects=await prisma.$queryRawUnsafe(`SELECT id,repository,name,description,url,metadata,last_observed_at AS "lastObservedAt" FROM world_model_projects WHERE $1='' OR name ILIKE $2 OR repository ILIKE $2 OR description ILIKE $2 ORDER BY last_observed_at DESC LIMIT $3`,query.trim(),q,limit);const technologies=await prisma.$queryRawUnsafe(`SELECT t.name,COUNT(*)::int AS "projectCount" FROM world_model_technologies t JOIN world_model_relationships r ON r.target_id=t.id WHERE $1='' OR t.name ILIKE $2 GROUP BY t.name ORDER BY "projectCount" DESC LIMIT $3`,query.trim(),q,limit);return{query,projects,technologies};}
export function verifyGitHubSignature(raw:string,signature:string|undefined){const secret=process.env.GITHUB_WEBHOOK_SECRET;if(!secret||!signature)return false;const expected=`sha256=${createHmac("sha256",secret).update(raw).digest("hex")}`,a=Buffer.from(expected),b=Buffer.from(signature);return a.length===b.length&&timingSafeEqual(a,b);}
export async function processWebhook(payload:any){if(!payload?.repository?.full_name)throw new Error("Webhook payload missing repository");const repo=await gh(`/repos/${payload.repository.full_name}`)as Repo;const changed=[...new Set<string>((payload.commits||[]).flatMap((c:any)=>[...(c.added||[]),...(c.modified||[]),...(c.removed||[])))];const result=await syncRepository(repo,undefined,changed.filter(p=>TEXT.test(p)));await prisma.$executeRawUnsafe(`INSERT INTO world_model_events(id,project_id,event_type,commit_sha,changed_paths,payload) VALUES($1,$2,'github_webhook',$3,$4::jsonb,$5::jsonb)`,key("webhook",`${repo.full_name}:${payload.after||Date.now()}`),result.projectId,payload.after||null,JSON.stringify(changed),JSON.stringify({action:payload.action,ref:payload.ref}));return result;}
