import { FormEvent, useState } from "react";
import { ArrowRight, BrainCircuit, GitBranch, Network, Search, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type Result={projects:any[];technologies:any[]};
export default function Navigator(){const[q,setQ]=useState("");const[result,setResult]=useState<Result|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState("");
 const search=async(e?:FormEvent)=>{e?.preventDefault();if(!q.trim())return;setLoading(true);setError("");try{const r=await fetch(`/api/world-model/navigator?q=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw new Error(d.error||"Navigator unavailable");setResult(d.data);}catch(err){setError(err instanceof Error?err.message:"Navigator unavailable");}finally{setLoading(false);}};
 return <main className="min-h-screen bg-background text-foreground"><section className="border-b border-border"><div className="mx-auto max-w-6xl px-6 py-20 lg:px-8"><Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← FEEXSYSTEMS</Link><div className="mt-10 max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-2 text-sm text-primary"><Sparkles className="h-4 w-4"/>World Model Navigator</div><h1 className="mt-6 text-5xl font-bold tracking-tight md:text-7xl">Ask the engineering world.</h1><p className="mt-5 text-lg leading-8 text-muted-foreground">Search the persistent World Model. Results are grounded in repository observations, artifacts, technologies and evidence—not generated project claims.</p></div><form onSubmit={search} className="mt-10 flex max-w-3xl gap-3"><div className="relative flex-1"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-muted-foreground"/><Input value={q} onChange={e=>setQ(e.target.value)} placeholder="e.g. Which projects use PostgreSQL?" className="h-14 pl-12 text-base"/></div><Button type="submit" disabled={loading} className="h-14 px-6">{loading?"Searching":"Explore"}<ArrowRight className="ml-2 h-4 w-4"/></Button></form></div></section>
 <section className="mx-auto max-w-6xl px-6 py-10 lg:px-8">{error&&<div className="mb-6 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm">{error}</div>}{result&&<div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2"><GitBranch className="h-5 w-5 text-primary"/>Projects</CardTitle></CardHeader><CardContent className="space-y-3">{result.projects.length?result.projects.map(p=><a key={p.id} href={p.url} target="_blank" rel="noreferrer" className="block rounded-xl border border-border p-4 transition hover:border-primary/40"><div className="font-semibold">{p.name}</div><div className="mt-1 text-sm text-muted-foreground">{p.repository}</div><div className="mt-2 text-sm text-muted-foreground">{p.description||"No description observed."}</div></a>):<p className="text-sm text-muted-foreground">No grounded project matches.</p>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2"><Network className="h-5 w-5 text-primary"/>Technology relationships</CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2">{result.technologies.length?result.technologies.map(t=><Badge key={t.name} variant="secondary">{t.name} · {t.projectCount}</Badge>):<p className="text-sm text-muted-foreground">No grounded technology matches.</p>}</CardContent></Card></div>}{!result&&!loading&&<div className="grid gap-5 md:grid-cols-3"><Card><CardContent className="p-6"><BrainCircuit className="h-6 w-6 text-primary"/><h3 className="mt-4 font-semibold">Canonical</h3><p className="mt-2 text-sm text-muted-foreground">The World Model is the source of truth.</p></CardContent></Card><Card><CardContent className="p-6"><GitBranch className="h-6 w-6 text-primary"/><h3 className="mt-4 font-semibold">Evidence-backed</h3><p className="mt-2 text-sm text-muted-foreground">Repository artifacts provide provenance.</p></CardContent></Card><Card><CardContent className="p-6"><Network className="h-6 w-6 text-primary"/><h3 className="mt-4 font-semibold">Graph-aware</h3><p className="mt-2 text-sm text-muted-foreground">Relationships connect projects to technologies.</p></CardContent></Card></div>}</section></main>;
}
