import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowUpRight, Boxes, ExternalLink, GitBranch, RefreshCw, Search, ShieldCheck, Sparkles } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { feexProjects } from "@/lib/feex-ecosystem";

type WorldProject={id:string;repository:string;name:string;description:string|null;url:string;metadata?:{language?:string;topics?:string[];stars?:number};lastObservedAt?:string};

export default function Projects(){
 const [query,setQuery]=useState("");const [projects,setProjects]=useState<WorldProject[]>([]);const [syncing,setSyncing]=useState(false);const [error,setError]=useState("");
 const load=async()=>{try{setError("");const r=await fetch("/api/world-model/projects");const d=await r.json();if(!r.ok||!d.success)throw new Error(d.error||"World Model unavailable");setProjects(d.projects||[]);}catch(e){setError(e instanceof Error?e.message:"World Model unavailable");}};
 useEffect(()=>{load();},[]);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();if(!q)return projects;return projects.filter(p=>[p.name,p.repository,p.description||"",p.metadata?.language||"",...(p.metadata?.topics||[])].join(" ").toLowerCase().includes(q));},[projects,query]);
 const sync=async()=>{setSyncing(true);try{await fetch("/api/world-model/sync/github-pinned",{method:"POST"});await load();}finally{setSyncing(false);}};
 const fallback=projects.length?projects:feexProjects.map(p=>({id:p.id,repository:`FeexSystems/${p.repository}`,name:p.name,description:p.description,url:`https://github.com/FeexSystems/${p.repository}`,metadata:{language:p.technologies[0],topics:p.technologies}}));
 const cards=query?visible:fallback;
 return <main className="min-h-screen bg-background text-foreground">
  <section className="relative overflow-hidden border-b border-border"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,hsl(var(--primary)/.16),transparent_35%),radial-gradient(circle_at_bottom_left,hsl(160_80%_45%/.10),transparent_30%)]"/><div className="relative mx-auto max-w-7xl px-6 py-20 lg:px-8 lg:py-28">
   <div className="mb-8 flex items-center gap-3 text-sm text-muted-foreground"><Link to="/" className="hover:text-foreground">FEEXSYSTEMS</Link><span>/</span><span>Projects</span></div>
   <div className="max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/10 px-4 py-2 text-sm font-medium text-primary"><Sparkles className="h-4 w-4"/>Living Engineering Intelligence</div><h1 className="text-5xl font-bold tracking-tight md:text-7xl">Explore the systems behind <span className="text-primary">FEEXSYSTEMS</span>.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-muted-foreground md:text-xl">GitHub repositories become engineering worlds: artifacts, technologies, relationships and evidence continuously synchronized into the FEEXSYSTEMS World Model.</p></div>
   <div className="mt-10 grid gap-4 sm:grid-cols-3"><Card className="bg-card/70"><CardContent className="p-5"><Boxes className="mb-3 h-5 w-5 text-primary"/><div className="text-3xl font-bold">{projects.length||feexProjects.length}</div><div className="text-sm text-muted-foreground">World Model projects</div></CardContent></Card><Card className="bg-card/70"><CardContent className="p-5"><GitBranch className="mb-3 h-5 w-5 text-primary"/><div className="text-3xl font-bold">Live</div><div className="text-sm text-muted-foreground">GitHub evidence pipeline</div></CardContent></Card><Card className="bg-card/70"><CardContent className="p-5"><ShieldCheck className="mb-3 h-5 w-5 text-primary"/><div className="text-3xl font-bold">Evidence-first</div><div className="text-sm text-muted-foreground">Canonical design principle</div></CardContent></Card></div>
  </div></section>
  <section className="mx-auto max-w-7xl px-6 py-10 lg:px-8"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><h2 className="text-2xl font-semibold">Engineering ecosystem</h2><p className="mt-1 text-sm text-muted-foreground">Pinned GitHub repositories are synchronized into the persistent World Model.</p></div><div className="flex gap-2"><div className="relative w-full lg:w-80"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, technologies..." className="pl-9"/></div><Button variant="outline" onClick={sync} disabled={syncing}>{syncing?<RefreshCw className="h-4 w-4 animate-spin"/>:<RefreshCw className="h-4 w-4"/>}<span className="ml-2 hidden sm:inline">Sync</span></Button></div></div>
   {error&&<div className="mt-5 rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-muted-foreground">Live World Model unavailable; showing the evidence-safe showcase registry. {error}</div>}
   <div className="mt-8 grid gap-6 md:grid-cols-2 xl:grid-cols-3">{cards.map(p=><Card key={p.id} className="group flex h-full flex-col border-border/80 transition-all hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl"><CardHeader><div className="flex items-start justify-between gap-4"><div className="rounded-xl border border-primary/20 bg-primary/10 p-3 text-primary"><Boxes className="h-5 w-5"/></div><Badge variant="outline">{projects.length?"World Model":"Showcase"}</Badge></div><CardTitle className="mt-4 text-xl">{p.name}</CardTitle><CardDescription className="leading-6">{p.description||"Engineering project discovered from the FeexSystems ecosystem."}</CardDescription></CardHeader><CardContent className="mt-auto space-y-5"><div className="flex items-center justify-between text-xs text-muted-foreground"><span>{p.metadata?.language||"Engineering world"}</span><span className="font-mono">{p.repository.split("/").pop()}</span></div><div className="flex flex-wrap gap-2">{(p.metadata?.topics||[]).slice(0,6).map(t=><Badge key={t} variant="secondary">{t}</Badge>)}</div><Button asChild className="w-full group-hover:bg-primary"><a href={p.url} target="_blank" rel="noreferrer">Inspect repository<ExternalLink className="ml-2 h-4 w-4"/></a></Button></CardContent></Card>)}</div>
   {!cards.length&&<div className="mt-10 rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground">No projects match this query.</div>}
   <div className="mt-12 rounded-2xl border border-primary/20 bg-primary/5 p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h3 className="font-semibold">Living pipeline</h3><p className="mt-1 text-sm text-muted-foreground">Pinned Repository → Repository Tree → Artifacts → Technologies → Relationships → Evidence → Incremental Webhook → World Model mutation → Navigator retrieval.</p></div><Button asChild variant="outline"><a href="https://github.com/FeexSystems/FeexSystems-20Labs" target="_blank" rel="noreferrer">View app source<ArrowUpRight className="ml-2 h-4 w-4"/></a></Button></div></div>
  </section></main>;
}
